variables:
  DOCKERHUB_REPO_NAME: alertmanager-telegram-bot
  ENABLE_ARM64: 'true'
  ENABLE_ARMv7: 'true'
  ENABLE_ARMv6: 'true'

include:
  - project: 'ix.ai/ci-templates'
    file: '/python-project.yml'
